create table wearehiring(
     sno int auto_increment primary key,
     fullname varchar(50),
     email varchar(50),
     phone int,
     subject text,
     message text,
     resume blob
);

create table publisher(
    username varchar(50) primary key,
    password varchar(100),
    title varchar(50),
    firstname varchar(50),
    middlename varchar(50),
    lastname varchar(50),
    position varchar(50),
    company varchar(50),
    curl varchar(50),
    entity varchar(50),
    model varchar(50),
    email varchar(50),
    phone varchar(100),
    landline int,
    country varchar(50),
    state varchar(50),
    city varchar(50),
    zipcode int,
    address text,
    skype varchar(50),
    heared text,
    wurl varchar(50),
    wcategory varchar(100),
    wlang varchar(50),
    uvpm int,
    pvpm int,
    gender varchar(50),
    vage varchar(50),
    adformat varchar(50),
    wurl1 varchar(50),
    wlang1 varchar(50),
    uvpm1 int,
    pvpm1 int,
    list text
);

create table advertiser(
    username varchar(50) primary key,
    password varchar(100),
    title varchar(50),
    firstname varchar(50),
    middlename varchar(50),
    lastname varchar(50),
    email varchar(50),
    phone varchar(100),
    landline int,
    country varchar(50),
    state varchar(50),
    city varchar(50),
    zipcode int,
    address text,
    position varchar(50),
    company varchar(50),
    curl varchar(50),
    whoami varchar(50),
    cprofile text,
    guidance text
);
